language: cpp
dist: bionic
compiler:
  - gcc
  # - clang 

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # Qt5 SVG
  - sudo apt-get install libqt5svg5-dev
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint.sh
  # valgrind, for helgrind and memcheck
  - sudo apt-get install -qq valgrind
  # SLOCcount
  - sudo apt-get install sloccount
  # Get my folder
  - my_github=${PWD##*/}  
  - ./download_other_githubs.sh
  - ./install_other_githubs.sh

script: 
  - qmake -qt=qt5 TwoDigitNewickTest.pro
  - make --silent debug
  - ./TwoDigitNewickTest
  - qmake -qt=qt5 TestTwoDigitNewickConsole.pro
  - make --silent debug
  - ./TestTwoDigitNewickConsole "(2,(2,2))" 10.0
  - qmake -qt=qt5 TestTwoDigitNewickDesktop.pro
  - make --silent debug
  - ./get_code_cov.sh >/dev/null
  - codecov >/dev/null
  - ./do_oclint.sh || true

after_success: 
  - bash <(curl -s https://codecov.io/bash)
