language: cpp
compiler: gcc

addons:
  # Boost
  apt: 
    packages: libboost-all-dev

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev libqt5svg5*
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # Qt5 SVG
  - sudo apt-get install libqt5svg5-dev
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # Codecov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-6 90
  - sudo pip install codecov
  # OCLint
  - ./install_oclint.sh
  # valgrind, for helgrind and memcheck
  - sudo apt-get install -qq valgrind
  # SLOCcount
  - sudo apt-get install sloccount
  # Get my folder
  - my_github=${PWD##*/}  
  - ./download_other_githubs.sh
  - ./install_other_githubs.sh

script: 
  - qmake -qt=qt5 TwoDigitNewickTest.pro
  - make --silent debug
  - ./TwoDigitNewickTest
  - qmake -qt=qt5 TestTwoDigitNewickConsole.pro
  - make --silent debug
  - ./TestTwoDigitNewickConsole "(2,(2,2))" 10.0
  - qmake -qt=qt5 TestTwoDigitNewickDesktop.pro
  - make --silent debug
  - ./get_code_cov.sh
  - codecov
  - ./do_oclint.sh || true

after_success: 
  - bash <(curl -s https://codecov.io/bash)
